curations:
  license_findings:
    - path: "xyz-models/src/main/java/com/here/xyz/models/hub/Space.java"
      reason: "DATA_OF"
      comment: "The file contains all possible license identifiers for the content of a space."
      concluded_license: "Apache-2.0"
    - path: "xyz-hub-service/src/main/resources/openapi/*"
      reason: "DATA_OF"
      comment: "The files found in this folder are part of the OpenAPI specification and could have license keywords, therefore they should be ignored by the OSS scanner."
      concluded_license: "Apache-2.0"
excludes:
  paths:
  - pattern: "xyz-hub-test/**"
    reason: "TEST_TOOL_OF"
    comment: "This directory only contains tests to verify correct functioning of XYZ Hub."
  scopes:
  - pattern: "provided"
    reason: "PROVIDED_DEPENDENCY_OF"
    comment: "Scope with dependencies provided by the JDK or container at runtime. Not included in released artifacts."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Scope with dependencies only used for testing. Not included in released artifacts."
resolutions:
  errors:
  - message: .*Timeout after 300 seconds while scanning file.*modules\/library\/sample-data\/src\/main\/resources\/org\/geotools\/test-data\/xml\/fme\/roads\/roads\.xml.*
    reason: "CANT_FIX_ISSUE"
    comment: "The issue refers to test data which is not present in the deployed version"
  - message: .*Timeout after 300 seconds while scanning file.*modules\/plugin\/epsg-wkt\/src\/main\/resources\/org\/geotools\/referencing\/crs\/epsg.properties.*"
    reason: "SCANNER_ISSUE"
    comment: "The issue is related to the scanner."
  - message: .*Timeout after 300 seconds while scanning file.*
    reason: "SCANNER_ISSUE"
    comment: "The issue is related to the scanner."
